spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C://Users/Holeski/OneDrive/附件/spider.db
    username: root
    password: 123456
  freemarker:
    # 禁用模板缓存
    cache: false
    # 编码格式
    charset: UTF-8
    # freemarker模板后缀 默认是 .ftl
    suffix: .ftl
    # 是否为此技术启用MVC视图分辨率。
    enabled: true
    # Content-Type值
    contentType: text/html
    # #模板加载路径 按需配置 ,默认路径是 classpath:/templates/
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##
  profiles:
    active: key
  jpa:
    database-platform: com.myself.spider.plantform.SQLiteDialect
    show-sql: true
    generate-ddl: true
    open-in-view: true

server:
  port: 9000
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

logging:
  level:
    com.myself.spider: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
